// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFJ_ul-_gaI32WWOGQtHmBJom2T0d44qE',
    appId: '1:556771067092:web:4c81cb25a16197bd8ce741',
    messagingSenderId: '556771067092',
    projectId: 'vibechat-f017e',
    authDomain: 'vibechat-f017e.firebaseapp.com',
    storageBucket: 'vibechat-f017e.firebasestorage.app',
    measurementId: 'G-LFS63KLGQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkSy0WeG5nfZ3ZVmExR2kNxcgM_afWJTs',
    appId: '1:556771067092:android:c2bec7d85ff100208ce741',
    messagingSenderId: '556771067092',
    projectId: 'vibechat-f017e',
    storageBucket: 'vibechat-f017e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTKZCM5jjdE95cOBJcUkfFsyG9ISkVfyY',
    appId: '1:556771067092:ios:4eec05a5767fcb5a8ce741',
    messagingSenderId: '556771067092',
    projectId: 'vibechat-f017e',
    storageBucket: 'vibechat-f017e.firebasestorage.app',
    iosBundleId: 'com.example.vibechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTKZCM5jjdE95cOBJcUkfFsyG9ISkVfyY',
    appId: '1:556771067092:ios:4eec05a5767fcb5a8ce741',
    messagingSenderId: '556771067092',
    projectId: 'vibechat-f017e',
    storageBucket: 'vibechat-f017e.firebasestorage.app',
    iosBundleId: 'com.example.vibechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFJ_ul-_gaI32WWOGQtHmBJom2T0d44qE',
    appId: '1:556771067092:web:b3516e04c37490268ce741',
    messagingSenderId: '556771067092',
    projectId: 'vibechat-f017e',
    authDomain: 'vibechat-f017e.firebaseapp.com',
    storageBucket: 'vibechat-f017e.firebasestorage.app',
    measurementId: 'G-LK43ZNBXYX',
  );
}
